#!/bin/bash

# The command below is adapted from https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

docker run --rm \
    --volume $PWD:/data \
    --user $(id -u):$(id -g) \
    --env JOURNAL=joss \
    openjournals/paperdraft
