#!/usr/bin/env python3

"""
This example computes a periodic field line that closes on itself only after
SEVERAL toroidal transits (``ntor > 1``) with SIMSOPT.

The magnetic axis of a stellarator closes after a single toroidal transit
(``ntor = 1``), but other periodic field lines need not: an X-point of an island
chain, for instance, may map to a different X-point each field period and only
return to itself after ``ntor`` transits. The curve representation used by
:class:`~simsopt.geo.periodicfieldline.PeriodicFieldLine`,
:class:`~simsopt.geo.CurveXYZFourierSymmetries`, supports this through its
``ntor`` argument.

Here we load a quasi-helical (QH) coil set and solve for two X-points that each
close after two toroidal transits (``ntor = 2``). Finding such a field line from
scratch requires tracing the field and searching for the fixed point of the
return map; to keep this example self-contained, good initial guesses (already
accurate periodic field lines) are stored in ``inputs/`` and loaded here, so the
undamped Newton solve of :meth:`PeriodicFieldLine.run_code` converges
immediately. The seeds were generated by field-line tracing and an arc-length
Fourier fit (see ``periodicfieldline.py`` for the magnetic-axis, ``ntor = 1``
case).
"""

import os
import json

import numpy as np

from simsopt._core import load
from simsopt.field import BiotSavart
from simsopt.geo import CurveXYZFourierSymmetries, CurveLength, curves_to_vtk
from simsopt.geo.periodicfieldline import PeriodicFieldLine

THIS_DIR = os.path.dirname(__file__)
INPUTS = os.path.join(THIS_DIR, "inputs")

# 1. Load the QH configuration (surfaces + coils) and assemble the Biot-Savart
#    field from the coils.
surfaces, coils = load(os.path.join(INPUTS, "serial2228222.json"))
bs = BiotSavart(coils)

# 2. Load the pre-computed seeds for the two ntor=2 X-points. Each seed stores
#    the curve parameters (nfp, ntor, stellsym, order) and its Fourier dofs.
with open(os.path.join(INPUTS, "QH_periodic_fieldline_seeds.json")) as f:
    seeds = json.load(f)

field_lines = []
for seed in seeds:
    # 3. Rebuild the seed curve. It is defined over a single field period,
    #    theta in [0, 1/nfp), with 2*order+1 quadpoints (a square Newton system).
    #    ntor=2 makes the curve wrap twice toroidally before closing.
    quadpoints = np.linspace(0, 1/seed["nfp"], 2*seed["order"]+1, endpoint=False)
    curve = CurveXYZFourierSymmetries(quadpoints, seed["order"], seed["nfp"],
                                      seed["stellsym"], ntor=seed["ntor"])
    curve.x = np.array(seed["dofs"])

    # 4. Solve for the periodic field line. Because the seed is already an
    #    accurate periodic field line, the (undamped) Newton solve converges
    #    immediately.
    fl = PeriodicFieldLine(BiotSavart(bs.coils), curve)
    res = fl.run_code(CurveLength(fl.curve).J())
    field_lines.append(fl)

    g0 = fl.curve.gamma()[0]
    print(f"{seed['label']}: success={res['success']}, iterations={res['iter']}, "
          f"length={res['length']:.6f} m, "
          f"start (R, Z) = ({np.hypot(g0[0], g0[1]):.5f}, {g0[2]:.5f}) m")

# 5. Save the coils and the periodic field lines for visualization (Paraview).
curves_to_vtk([c.curve for c in coils], "QH_coils")
curves_to_vtk([fl.curve for fl in field_lines], "QH_periodic_field_lines", close=True)
