#!/usr/bin/env python
r"""
This example script optimizes a set of relatively simple toroidal field coils
and passive superconducting coils (PSCs)
for an ARIES-CS reactor-scale version of the precise-QH stellarator from 
Landreman and Paul. 

The script should be run as:
    mpirun -n 1 python QH_psc_example.py
on a cluster machine but 
    python QH_psc_example.py
is sufficient on other machines. Note that this code does not use MPI, but is 
parallelized via OpenMP, so will run substantially
faster on multi-core machines (make sure that all the cores
are available to OpenMP, e.g. through setting OMP_NUM_THREADS).

"""
from pathlib import Path

import numpy as np
from scipy.optimize import minimize
from matplotlib import pyplot as plt
from simsopt.field import BiotSavart, Current, coils_via_symmetries
from simsopt.geo import SurfaceRZFourier, curves_to_vtk
from simsopt.geo.psc_grid import PSCgrid
from simsopt.objectives import SquaredFlux
from simsopt.util import in_github_actions
from simsopt.util.permanent_magnet_helper_functions import *
import time
import shutil

def coil_optimization_QA(s, bs, base_curves, curves, out_dir=''):
    """
    Optimize the coils for the Landreman-Paul QA configuration.

    Args:
        s: plasma boundary.
        bs: Biot Savart class object, presumably representing the
          magnetic fields generated by the coils.
        base_curves: List of CurveXYZFourier class objects.
        curves: List of Curve class objects.
        out_dir: Path or string for the output directory for saved files.

    Returns:
        bs: Biot Savart class object, presumably representing the
          OPTIMIZED magnetic fields generated by the coils.
    """

    from simsopt.geo import CurveLength, CurveCurveDistance, \
        MeanSquaredCurvature, LpCurveCurvature, CurveSurfaceDistance
    from simsopt.objectives import QuadraticPenalty

    out_dir = Path(out_dir)
    nphi = len(s.quadpoints_phi)
    ntheta = len(s.quadpoints_theta)
    ncoils = len(base_curves)

    # Weight on the curve lengths in the objective function:
    LENGTH_WEIGHT = 0.05

    # Threshold and weight for the coil-to-coil distance penalty in the objective function:
    CC_THRESHOLD = 1.0
    CC_WEIGHT = 1e1

    # Threshold and weight for the coil-to-surface distance penalty in the objective function:
    CS_THRESHOLD = 3.7
    CS_WEIGHT = 1e0

    # Threshold and weight for the curvature penalty in the objective function:
    CURVATURE_THRESHOLD = 0.1
    CURVATURE_WEIGHT = 1e1

    # Threshold and weight for the mean squared curvature penalty in the objective function:
    MSC_THRESHOLD = 0.1
    MSC_WEIGHT = 1e1

    MAXITER = 1000  # number of iterations for minimize

    # Define the objective function:
    Jf = SquaredFlux(s, bs)
    Jls = [CurveLength(c) for c in base_curves]
    Jccdist = CurveCurveDistance(curves, CC_THRESHOLD, num_basecurves=ncoils)
    Jcsdist = CurveSurfaceDistance(curves, s, CS_THRESHOLD)
    Jcs = [LpCurveCurvature(c, 2, CURVATURE_THRESHOLD) for c in base_curves]
    Jmscs = [MeanSquaredCurvature(c) for c in base_curves]

    # Form the total objective function.
    JF = Jf \
        + LENGTH_WEIGHT * sum(Jls) \
        + CC_WEIGHT * Jccdist \
        + CS_WEIGHT * Jcsdist \
        + CURVATURE_WEIGHT * sum(Jcs) \
        + MSC_WEIGHT * sum(QuadraticPenalty(J, MSC_THRESHOLD) for J in Jmscs)

    def fun(dofs):
        """ Function for coil optimization grabbed from stage_two_optimization.py """
        JF.x = dofs
        J = JF.J()
        grad = JF.dJ()
        jf = Jf.J()
        BdotN = np.mean(np.abs(np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)))
        outstr = f"J={J:.3e}, Jf={jf:.3e}, ⟨B·n⟩={BdotN:.3e}"
        cl_string = ", ".join([f"{J.J():.3f}" for J in Jls])
        kap_string = ", ".join(f"{np.max(c.kappa()):.3f}" for c in base_curves)
        msc_string = ", ".join(f"{J.J():.3f}" for J in Jmscs)
        outstr += f", Len=sum([{cl_string}])={sum(J.J() for J in Jls):.3f}, ϰ=[{kap_string}], ∫ϰ²/L=[{msc_string}]"
        outstr += f", C-C-Sep={Jccdist.shortest_distance():.3f}, C-S-Sep={Jcsdist.shortest_distance():.3f}"
        outstr += f", ║∇J║={np.linalg.norm(grad):.3e}"
        print(outstr)
        return J, grad

    print("""
    ################################################################################
    ### Perform a Taylor test ######################################################
    ################################################################################
    """)
    f = fun
    dofs = JF.x
    h = np.random.uniform(size=dofs.shape)

    J0, dJ0 = f(dofs)
    dJh = sum(dJ0 * h)
    for eps in [1e-3, 1e-4, 1e-5, 1e-6, 1e-7]:
        J1, _ = f(dofs + eps*h)
        J2, _ = f(dofs - eps*h)
        print("err", (J1-J2)/(2*eps) - dJh)

    print("""
    ################################################################################
    ### Run the optimisation #######################################################
    ################################################################################
    """)
    minimize(fun, dofs, jac=True, method='L-BFGS-B', options={'maxiter': MAXITER, 'maxcor': 1000}, tol=1e-8)
    bs.set_points(s.gamma().reshape((-1, 3)))
    return bs

t1 = time.time()
np.random.seed(1)  # set a seed so that the same PSCs are initialized each time

# Set some parameters -- if doing CI, lower the resolution
if in_github_actions:
    nphi = 4  # nphi = ntheta >= 64 needed for accurate full-resolution runs
    ntheta = nphi
else:
    # Resolution needs to be reasonably high if you are doing permanent magnets
    # or small coils because the fields are quite local
    nphi = 64  # nphi = ntheta >= 64 needed for accurate full-resolution runs
    ntheta = nphi
    # Make higher resolution surface for plotting Bnormal
    qphi = nphi * 2
    quadpoints_phi = np.linspace(0, 1, qphi, endpoint=True)
    quadpoints_theta = np.linspace(0, 1, ntheta * 2, endpoint=True)

poff = 1.5  # PSC grid will be offset 'poff' meters from the plasma surface
coff = 1.6  # PSC grid will be initialized between 1 m and 2 m from plasma

# Read in the plasma equilibrium file
input_name = 'input.LandremanPaul2021_QA_reactorScale_lowres'
TEST_DIR = (Path(__file__).parent / ".." / ".." / "tests" / "test_files").resolve()
surface_filename = TEST_DIR / input_name
range_param = 'half period'
s = SurfaceRZFourier.from_vmec_input(
    surface_filename, range=range_param, nphi=nphi, ntheta=ntheta
)
# Print major and minor radius
print('s.R = ', s.get_rc(0, 0))
print('s.r = ', s.get_rc(1, 0))

# Make inner and outer toroidal surfaces very high resolution,
# which helps to initialize coils precisely between the surfaces. 
s_inner = SurfaceRZFourier.from_vmec_input(
    surface_filename, range=range_param, nphi=nphi * 8, ntheta=ntheta * 8
)
s_outer = SurfaceRZFourier.from_vmec_input(
    surface_filename, range=range_param, nphi=nphi * 8, ntheta=ntheta * 8
)

# Make the inner and outer surfaces by extending the plasma surface
s_inner.extend_via_normal(poff)
s_outer.extend_via_normal(poff + coff)

# Remake the output directory and erase previous files (to avoid confusion)
out_str = "QA_psc_GPMO/"
try:
    shutil.rmtree(out_str)
except OSError as e:
    print("Error: %s - %s." % (e.filename, e.strerror))
out_dir = Path("QA_psc_GPMO")
out_dir.mkdir(parents=True, exist_ok=True)

# Save the inner and outer surfaces for debugging purposes
s_inner.to_vtk(out_str + 'inner_surf')
s_outer.to_vtk(out_str + 'outer_surf')


def initialize_coils_qa():
    from simsopt.geo import create_equally_spaced_curves
    from simsopt.field import Current, coils_via_symmetries
    from simsopt.mhd.vmec import Vmec
    
    # generate planar TF coils
    ncoils = 2
    R0 = s.get_rc(0, 0)
    R1 = s.get_rc(1, 0) * 5
    order = 4

    # qa needs to be scaled to 5.7 T on-axis magnetic field strength
    vmec_file = 'wout_LandremanPaul2021_QA_reactorScale_lowres_reference.nc'
    total_current = Vmec(TEST_DIR / vmec_file).external_current() / (2 * s.nfp) / 7.131 * 6 / 1.01
    base_curves = create_equally_spaced_curves(ncoils, s.nfp, stellsym=True, R0=R0, R1=R1, order=order, numquadpoints=64)
    base_currents = [(Current(total_current / ncoils * 1e-5) * 1e5) for _ in range(ncoils - 1)]
    # base_currents[0].fix_all()
    total_current = Current(total_current)
    total_current.fix_all()
    base_currents += [total_current - sum(base_currents)]
    coils = coils_via_symmetries(base_curves, base_currents, s.nfp, True)
    # fix all the coil shapes so only the currents are optimized
    # for i in range(ncoils):
    #     base_curves[i].fix_all()
    # Initialize the coil curves and save the data to vtk
    curves = [c.curve for c in coils]
    curves_to_vtk(curves, out_dir / "curves_init")
    return base_curves, curves, coils

# initialize the coils
base_curves, curves, coils = initialize_coils_qa()
currents = np.array([coil.current.get_value() for coil in coils])
print('Currents = ', currents)

# Set up BiotSavart fields
bs = BiotSavart(coils)

# Calculate average, approximate on-axis B field strength
calculate_on_axis_B(bs, s)

# Make high resolution, full torus version of the plasma boundary for plotting
s_plot = SurfaceRZFourier.from_vmec_input(
    surface_filename, 
    quadpoints_phi=quadpoints_phi, 
    quadpoints_theta=quadpoints_theta
)
s_plot.save(filename=out_dir / 'plasma_boundary.json')

# Plot initial Bnormal on plasma surface from un-optimized BiotSavart coils
make_Bnormal_plots(bs, s_plot, out_dir, "biot_savart_initial")

# optimize the currents in the TF coils and plot results
bs = coil_optimization_QA(s, bs, base_curves, curves, out_dir)
bs.save('B_TF.json')
currents = np.array([coil.current.get_value() for coil in coils])
curves_to_vtk(curves, out_dir / "TF_coils", close=True)
bs.set_points(s.gamma().reshape((-1, 3)))
Bnormal = np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)
make_Bnormal_plots(bs, s_plot, out_dir, "biot_savart_TF_optimized")

# check after-optimization average on-axis magnetic field strength
B_axis = calculate_on_axis_B(bs, s)
make_Bnormal_plots(bs, s_plot, out_dir, "biot_savart_TF_optimized", B_axis)

# Finally, initialize the psc class
kwargs_geo = {"Nx": 10, "out_dir": out_str,
              # "initialization": "plasma", 
              "poff": poff,}
              # "interpolated_field": True} 
psc_array = PSCgrid.geo_setup_between_toroidal_surfaces(
    s, coils, s_inner, s_outer,  **kwargs_geo
)
print('Number of PSC locations = ', len(psc_array.grid_xyz))

currents = []
for i in range(psc_array.num_psc):
    currents.append(Current(psc_array.I[i]))
all_coils = coils_via_symmetries(
    psc_array.curves, currents, nfp=psc_array.nfp, stellsym=psc_array.stellsym
)
B_PSC = BiotSavart(all_coils)
# Plot initial errors from only the PSCs, and then together with the TF coils
make_Bnormal_plots(B_PSC, s_plot, out_dir, "biot_savart_PSC_initial", B_axis)
make_Bnormal_plots(bs + B_PSC, s_plot, out_dir, "PSC_and_TF_initial", B_axis)

# Check SquaredFlux values using different ways to calculate it
x0 = np.ravel(np.array([psc_array.alphas, psc_array.deltas]))
fB = SquaredFlux(s, bs, np.zeros((nphi, ntheta))).J()
fB_TF = fB / (B_axis ** 2 * s.area())
print('fB only TF coils = ', fB_TF)
bs.set_points(s.gamma().reshape(-1, 3))
Bnormal = np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)
print('fB only TF direct = ', np.sum(Bnormal.reshape(-1) ** 2 * psc_array.grid_normalization ** 2
                                    ) / (2 * B_axis ** 2 * s.area()))
make_Bnormal_plots(B_PSC, s_plot, out_dir, "biot_savart_PSC_initial", B_axis)
fB = SquaredFlux(s, B_PSC, np.zeros((nphi, ntheta))).J()
print(fB/ (B_axis ** 2 * s.area()))
fB = SquaredFlux(s, B_PSC + bs, np.zeros((nphi, ntheta))).J()
print('fB with both, before opt = ', fB / (B_axis ** 2 * s.area()))
fB = SquaredFlux(s, B_PSC, -Bnormal).J()
print('fB with both (minus sign), before opt = ', fB / (B_axis ** 2 * s.area()))

# Actually do the minimization now
print('beginning optimization: ')
# Start with zero PSCs and list of all admissible ones
eps = 1e-6
pi = np.pi - eps
alphas_admissible = np.array([0, 0, -pi / 2.0, pi / 2.0, 0, 0])
deltas_admissible = np.array([pi / 2.0, -pi / 2.0, 0, 0, 0, pi])

# Start GPMO loop
admissible_pscs = np.arange(psc_array.num_psc)
placed_pscs = []
kwargs_manual = {
                 "out_dir": out_str, 
                 "plasma_boundary" : s,
                 "coils_TF" : coils
                 }
num_placements = psc_array.num_psc
BdotN2_list = []
Bn_list = []
kappas_k = np.zeros(2)
for j in range(num_placements):
    t1 = time.time()
    if j != 0:
        kappas_k = np.insert(kappas_k, [j, 2 * j], 0.0)
    BdotN2_min = 1e10
    Bn_mag_min = 1e10
    min_k_ind = 0
    min_i_ind = 0
    for k in admissible_pscs:
        current_inds = placed_pscs + [k]
        # print(j, k, current_inds, placed_pscs)
        psc_temp = PSCgrid.geo_setup_manual(
            psc_array.grid_xyz[current_inds, :], psc_array.R, **kwargs_manual
        )
        # print(psc_temp.num_psc)
        for i in range(6):
            kappas_k[j] = alphas_admissible[i]
            kappas_k[j + psc_temp.num_psc] = deltas_admissible[i]
            # psc_temp.least_squares()
            psc_temp.setup_orientations(kappas_k[:psc_temp.num_psc], kappas_k[psc_temp.num_psc:])
            psc_temp.update_psi()
            psc_temp.setup_currents_and_fields()
            Ax_b = (psc_temp.Bn_PSC + psc_temp.b_opt) * psc_temp.grid_normalization
            Bn_mag = np.sum(np.abs((psc_temp.Bn_PSC + psc_temp.b_opt) * psc_temp.grid_normalization ** 2))
            Bn_mag = Bn_mag * psc_temp.fac / psc_temp.Baxis_A
            BdotN2 = (Ax_b.T @ Ax_b) * psc_temp.fac2_norm2
            if BdotN2 < BdotN2_min:
                BdotN2_min = BdotN2
                Bn_mag_min = Bn_mag
                min_k_ind = k
                min_i_ind = i
                min_j_ind = j
        # unset those variables
        kappas_k[j] = 0.0
        kappas_k[j + psc_temp.num_psc] = 0.0
    kappas_k[min_j_ind] = alphas_admissible[min_i_ind]
    kappas_k[min_j_ind + psc_temp.num_psc] = deltas_admissible[min_i_ind]
    BdotN2_list.append(BdotN2_min)
    Bn_list.append(Bn_mag_min)
    print('Iteration ', j, ' fB = ', BdotN2_min)
    # print(psc_temp.num_psc, placed_pscs)
    # print(kappas_k)
    # k_remainder = min_k_ind % 6
    # remove_inds = np.arange(min_k_ind - k_remainder, min_k_ind + 6 - k_remainder)
    # print('min_k_ind = ', min_k_ind, k_remainder)
    # print('remove = ', remove_inds)
    admissible_pscs = np.setdiff1d(admissible_pscs, min_k_ind)
    # print('admissible = ', admissible_pscs)
    # exit()
    placed_pscs.append(min_k_ind)
    
    if j % 5 == 0:
        psc_temp.setup_curves()
        psc_temp.plot_curves('coils_{0:d}'.format(j + 1) + '_')
        currents = []
        for i in range(psc_temp.num_psc):
            currents.append(Current(psc_temp.I[i]))
        all_coils = coils_via_symmetries(
            psc_temp.curves, currents, nfp=psc_temp.nfp, stellsym=psc_temp.stellsym
        )
        B_PSC = BiotSavart(all_coils)
        B_tot = bs + B_PSC
        # B_tot.save('B_{0:d}'.format(j + 1) + '.json')
        make_Bnormal_plots(B_tot, s_plot, out_dir, 'B_{0:d}'.format(j + 1), B_axis)
    t2 = time.time()
    print('Time for that iteration = ', t2 - t1)
psc_temp.kappas = kappas_k
# psc_array.GPMO_PSC_arrays()
# Bn_list = psc_array.Bn_list
# BdotN2_list = psc_array.BdotN2_list

# Plot the data from optimization
BdotN2_list = np.ravel(BdotN2_list)
Bn_list = np.ravel(Bn_list)
fig, ax1 = plt.subplots()
color = 'b'
ax1.set_xlabel('Iterations')
ax1.set_ylabel(r'$f_B$', color=color)
ax1.semilogy(BdotN2_list, color=color)
ax1.semilogy(Bn_list, color + '--', label=r'$b_n$')
ax1.semilogy(0.005 * np.ones(len(Bn_list)), 'm--', label=r'$b_n$, benchmark')
ax1.plot(fB_TF * np.ones(len(BdotN2_list)), 'k--', label=r'$f_B$, TF coils only')
ax1.grid()
ax1.tick_params(axis='y', labelcolor=color)
ax1.legend()
plt.savefig(out_dir / 'convergence.jpg')

# Last check that direct f_B calculation is still consistent with the optimization
psc_array.setup_curves()
psc_array.plot_curves('final_')
currents = []
for i in range(psc_array.num_psc):
    currents.append(Current(psc_array.I[i]))
all_coils = coils_via_symmetries(
    psc_array.curves, currents, nfp=psc_array.nfp, stellsym=psc_array.stellsym
)
B_PSC = BiotSavart(all_coils)
fB = SquaredFlux(s, B_PSC + bs, np.zeros((nphi, ntheta))).J()
print('fB with both, after opt = ', fB / (B_axis ** 2 * s.area()))
make_Bnormal_plots(B_PSC, s_plot, out_dir, "PSC_final", B_axis)
make_Bnormal_plots(bs + B_PSC, s_plot, out_dir, "PSC_and_TF_final", B_axis)
t2 = time.time()
print('Total time: ', t2 - t1)
plt.show()

