#!/usr/bin/env python
r"""
This example script optimizes a set of relatively simple toroidal field coils
and passive superconducting coils (PSCs)
for an ARIES-CS reactor-scale version of the precise-QH stellarator from 
Landreman and Paul. 

The script should be run as:
    mpirun -n 1 python QH_psc_example.py
on a cluster machine but 
    python QH_psc_example.py
is sufficient on other machines. Note that this code does not use MPI, but is 
parallelized via OpenMP, so will run substantially
faster on multi-core machines (make sure that all the cores
are available to OpenMP, e.g. through setting OMP_NUM_THREADS).

"""
from pathlib import Path

import numpy as np
from scipy.optimize import minimize
from matplotlib import pyplot as plt
from simsopt.field import BiotSavart, Current, coils_via_symmetries
from simsopt.geo import SurfaceRZFourier, curves_to_vtk
from simsopt.geo.psc_grid import PSCgrid
from simsopt.objectives import SquaredFlux
from simsopt.util import in_github_actions
from simsopt.util.permanent_magnet_helper_functions import *
import time
import shutil

def coil_optimization_QA(s, bs, base_curves, curves, psc_array=None, MAXITER=1000, jac_flag=True):
    """
    Optimize the coils for the Landreman-Paul QA configuration.

    Args:
        s: plasma boundary.
        bs: Biot Savart class object, presumably representing the
          magnetic fields generated by the coils.
        base_curves: List of CurveXYZFourier class objects.
        curves: List of Curve class objects.
        out_dir: Path or string for the output directory for saved files.

    Returns:
        bs: Biot Savart class object, presumably representing the
          OPTIMIZED magnetic fields generated by the coils.
    """

    from simsopt.geo import CurveLength, CurveCurveDistance, \
        MeanSquaredCurvature, LpCurveCurvature, CurveSurfaceDistance
    from simsopt.objectives import QuadraticPenalty
    
    BdotN2_list = []
    Bn_list = []
    # try:
    #     grid = grid_xyz_copy 
    # except:
    #     grid = grid_xyz
    if psc_array is not None:
        # B_PSC = BiotSavart(psc_array.psc_coils)
        # B_PSC.set_points(s.gamma().reshape(-1, 3))
        Nnorms = np.sqrt(np.sum(s.normal() ** 2, axis=-1))

    nphi = len(s.quadpoints_phi)
    ntheta = len(s.quadpoints_theta)
    ncoils = len(base_curves)

    # Weight on the curve lengths in the objective function:
    LENGTH_WEIGHT = 1

    # Threshold and weight for the coil-to-coil distance penalty in the objective function:
    CC_THRESHOLD = 1.5
    CC_WEIGHT = 1e2

    # Threshold and weight for the coil-to-surface distance penalty in the objective function:
    CS_THRESHOLD = 3.7
    CS_WEIGHT = 1e1  # 1e-1

    # Threshold and weight for the curvature penalty in the objective function:
    CURVATURE_THRESHOLD = 0.1
    CURVATURE_WEIGHT = 1e-5

    # Threshold and weight for the mean squared curvature penalty in the objective function:
    MSC_THRESHOLD = 0.1
    MSC_WEIGHT = 1e-5

    # Define the objective function:
    # else:
        # psc_array.setup_curves()
        # currents = []
        # for i in range(psc_array.num_psc):
        #     currents.append(Current(psc_array.I[i]))
        # all_coils = coils_via_symmetries(
        #     psc_array.curves, currents, nfp=psc_array.nfp, stellsym=psc_array.stellsym
        # )
        # b_psc = BiotSavart(all_coils)
        # Jf = SquaredFlux(s, bs + b_psc)
        # kwargs_manual = {
        #                  "out_dir": out_str, 
        #                  "plasma_boundary" : s,
        #                  "coils_TF" : coils
        #                  }
    Jls = [CurveLength(c) for c in base_curves]
    Jccdist = CurveCurveDistance(curves, CC_THRESHOLD, num_basecurves=ncoils)
    Jcsdist = CurveSurfaceDistance(curves, s, CS_THRESHOLD)
    Jcs = [LpCurveCurvature(c, 2, CURVATURE_THRESHOLD) for c in base_curves]
    Jmscs = [MeanSquaredCurvature(c) for c in base_curves]

    if psc_array is None:
        Jf = SquaredFlux(s, bs)
        # Form the total objective function. Dropped Jf, be careful!
        JF = Jf + LENGTH_WEIGHT * sum(Jls) \
            + CC_WEIGHT * Jccdist \
            + CS_WEIGHT * Jcsdist \
            + CURVATURE_WEIGHT * sum(Jcs) \
            + MSC_WEIGHT * sum(QuadraticPenalty(J, MSC_THRESHOLD) for J in Jmscs)
    else:
        # base_currents = [Current(0.0) for _ in range(ncoils)]
        # coils_dummy = coils_via_symmetries(base_curves, base_currents, s.nfp, True)
        # b_dummy = BiotSavart(coils_dummy)
        Jf = SquaredFlux(s, bs + psc_array.B_PSC)
        # Jf = SquaredFlux(s, b_dummy)
        JF = Jf + LENGTH_WEIGHT * sum(Jls) \
            + CC_WEIGHT * Jccdist \
            + CS_WEIGHT * Jcsdist \
            + CURVATURE_WEIGHT * sum(Jcs) \
            + MSC_WEIGHT * sum(QuadraticPenalty(J, MSC_THRESHOLD) for J in Jmscs)

    def fun(dofs):
        """ Function for coil optimization grabbed from stage_two_optimization.py """
        JF.x = dofs
        J = JF.J()
        grad = JF.dJ()
        if psc_array is None:
            BdotN = np.mean(np.abs(np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)))
            jf = Jf.J()
            outstr = f"J={J:.3e}, Jf={jf:.3e}, ⟨B·n⟩={BdotN:.3e}"
        else:
            # coils = coils_via_symmetries(base_curves, base_currents, s.nfp, True)
            psc_array.update_TF(bs._coils)
            # all_coils = coils_via_symmetries(
            #     psc_array.curves, psc_array.currents, nfp=s.nfp, stellsym=s.stellsym
            # )
            # B_PSC = BiotSavart(all_coils)
            # B_PSC.set_points(s.gamma().reshape(-1, 3))
            
            #################### Add PSC contribution to fB 
            # jf = SquaredFlux(s, bs + B_PSC).J()
            
            # Add Bn2 contribution from PSCs
            # J += SquaredFlux(s, B_PSC).J()
            # Add cross term between PSCs and TF coils
            # Bn_PSC = np.sum(B_PSC.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)
            # Bn_TF = np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)
            # cross_term = np.sum(np.sum(Bn_TF * Bn_PSC * Nnorms)
            #                 ) / (len(s.quadpoints_phi) * len(s.quadpoints_theta)) 
            # jf = SquaredFlux(s, bs).J() + SquaredFlux(s, B_PSC).J() + cross_term
            jf = Jf.J()
            print('diff = ', jf - SquaredFlux(s, bs).J())
            # J += cross_term
            # print(JF)
            # JF -= SquaredFlux(s, bs).J()
            # JF += SquaredFlux(s, bs + B_PSC).J()
            # print(Jf.J(), SquaredFlux(s, B_PSC).J(), np.sum(np.sum(Bn_TF * Bn_PSC * Nnorms)
            #                 ) / (len(s.quadpoints_phi) * len(s.quadpoints_theta)) )
            
            # Add PSC contribution to grad
            # grad += SquaredFlux(s, bs + B_PSC).dJ()
            # Get rid of the pure B_TF gradient?
            # grad -= SquaredFlux(s, bs).dJ() 
            # Add in the gradient from the PSC part
            # grad += bs.B_vjp(psc_array.grad_TF())(JF + SquaredFlux(s, B_PSC))  # Almost certainly wrong! 
            BdotN = np.mean(np.abs(np.sum((bs.B() + psc_array.B_PSC.B()).reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2) * Nnorms)
                            ) / (len(s.quadpoints_phi) * len(s.quadpoints_theta)) 
            B_axis = calculate_on_axis_B(bs, s, print_out=False)
            bs.set_points(s.gamma().reshape(-1, 3))
            Jfnormed = jf / (B_axis ** 2 * s.area())
            Bnnormed = BdotN / (B_axis * s.area())
            BdotN2_list.append(Jfnormed)
            Bn_list.append(Bnnormed)
            outstr = f"J={J:.3e}, Jf={Jfnormed:.3e}, ⟨B·n⟩={Bnnormed:.3e}"
        cl_string = ", ".join([f"{J.J():.3f}" for J in Jls])
        kap_string = ", ".join(f"{np.max(c.kappa()):.3f}" for c in base_curves)
        msc_string = ", ".join(f"{J.J():.3f}" for J in Jmscs)
        outstr += f", Len=sum([{cl_string}])={sum(J.J() for J in Jls):.3f}, ϰ=[{kap_string}], ∫ϰ²/L=[{msc_string}]"
        outstr += f", C-C-Sep={Jccdist.shortest_distance():.3f}, C-S-Sep={Jcsdist.shortest_distance():.3f}"
        outstr += f", ║∇J║={np.linalg.norm(grad):.3e}"
        print(outstr)
        if jac_flag:
            return J, grad
        else:
            return J

    # print("""
    # ################################################################################
    # ### Perform a Taylor test ######################################################
    # ################################################################################
    # """)
    f = fun
    dofs = JF.x
    h = np.random.uniform(size=dofs.shape)

    J0, dJ0 = f(dofs)
    dJh = sum(dJ0 * h)
    for eps in [1e-3, 1e-4, 1e-5, 1e-6, 1e-7]:
        J1, _ = f(dofs + eps*h)
        J2, _ = f(dofs - eps*h)
        print("err", (J1-J2)/(2*eps) - dJh)

    print("""
    ################################################################################
    ### Run the optimisation #######################################################
    ################################################################################
    """)
    if jac_flag:
        minimize(fun, dofs, jac=True, method='L-BFGS-B', options={'maxiter': MAXITER, 'maxcor': 100}, tol=1e-6)
    else:
        minimize(fun, dofs, jac=False, method='L-BFGS-B', options={'maxiter': MAXITER}, tol=1e-6)
    bs.set_points(s.gamma().reshape((-1, 3)))
    return bs, BdotN2_list, Bn_list, psc_array

t1 = time.time()
np.random.seed(1)  # set a seed so that the same PSCs are initialized each time

# Set some parameters -- if doing CI, lower the resolution
if in_github_actions:
    nphi = 4  # nphi = ntheta >= 64 needed for accurate full-resolution runs
    ntheta = nphi
else:
    # Resolution needs to be reasonably high if you are doing permanent magnets
    # or small coils because the fields are quite local
    nphi = 64  # nphi = ntheta >= 64 needed for accurate full-resolution runs
    ntheta = nphi
    # Make higher resolution surface for plotting Bnormal
    qphi = nphi * 2
    quadpoints_phi = np.linspace(0, 1, qphi, endpoint=True)
    quadpoints_theta = np.linspace(0, 1, ntheta * 2, endpoint=True)

poff = 1.5  # PSC grid will be offset 'poff' meters from the plasma surface
coff = 1.25  # PSC grid will be initialized between 1 m and 2 m from plasma

# Read in the plasma equilibrium file
input_name = 'input.LandremanPaul2021_QA_reactorScale_lowres'
TEST_DIR = (Path(__file__).parent / ".." / ".." / "tests" / "test_files").resolve()
surface_filename = TEST_DIR / input_name
range_param = 'half period'
s = SurfaceRZFourier.from_vmec_input(
    surface_filename, range=range_param, nphi=nphi, ntheta=ntheta
)
# Print major and minor radius
print('s.R = ', s.get_rc(0, 0))
print('s.r = ', s.get_rc(1, 0))

# Make inner and outer toroidal surfaces very high resolution,
# which helps to initialize coils precisely between the surfaces. 
s_inner = SurfaceRZFourier.from_vmec_input(
    surface_filename, range=range_param, nphi=nphi * 8, ntheta=ntheta * 8
)
s_outer = SurfaceRZFourier.from_vmec_input(
    surface_filename, range=range_param, nphi=nphi * 8, ntheta=ntheta * 8
)

# Make the inner and outer surfaces by extending the plasma surface
s_inner.extend_via_normal(poff)
s_outer.extend_via_normal(poff + coff)

# Remake the output directory and erase previous files (to avoid confusion)
out_str = "QA_psc_TF/"
try:
    shutil.rmtree(out_str)
except OSError as e:
    print("Error: %s - %s." % (e.filename, e.strerror))
out_dir = Path("QA_psc_TF")
out_dir.mkdir(parents=True, exist_ok=True)

# Save the inner and outer surfaces for debugging purposes
s_inner.to_vtk(out_str + 'inner_surf')
s_outer.to_vtk(out_str + 'outer_surf')


def initialize_coils_qa():
    from simsopt.geo import create_equally_spaced_curves
    from simsopt.field import Current, coils_via_symmetries
    from simsopt.mhd.vmec import Vmec
    
    # generate planar TF coils
    ncoils = 3
    R0 = s.get_rc(0, 0)
    R1 = s.get_rc(1, 0) * 5
    order = 1

    # qa needs to be scaled to 5.7 T on-axis magnetic field strength
    vmec_file = 'wout_LandremanPaul2021_QA_reactorScale_lowres_reference.nc'
    total_current = Vmec(TEST_DIR / vmec_file).external_current() / (2 * s.nfp) * 0.85  #  / 7.131 * 6 / 1.01
    base_curves = create_equally_spaced_curves(ncoils, s.nfp, stellsym=True, R0=R0, R1=R1, order=order, numquadpoints=64)
    base_currents = [(Current(total_current / ncoils * 1e-5) * 1e5) for _ in range(ncoils - 1)]
    # base_currents[0].fix_all()
    total_current = Current(total_current)
    total_current.fix_all()
    base_currents += [total_current - sum(base_currents)]
    coils = coils_via_symmetries(base_curves, base_currents, s.nfp, True)
    # fix all the coil shapes so only the currents are optimized
    # for i in range(ncoils):
    #     base_curves[i].fix_all()
    # Initialize the coil curves and save the data to vtk
    curves = [c.curve for c in coils]
    curves_to_vtk(curves, out_dir / "curves_init")
    return base_curves, curves, coils

# initialize the coils
base_curves, curves, coils = initialize_coils_qa()
currents = np.array([coil.current.get_value() for coil in coils])
print('Currents = ', currents)

# Set up BiotSavart fields
bs = BiotSavart(coils)

# Calculate average, approximate on-axis B field strength
calculate_on_axis_B(bs, s)

# Make high resolution, full torus version of the plasma boundary for plotting
s_plot = SurfaceRZFourier.from_vmec_input(
    surface_filename, 
    quadpoints_phi=quadpoints_phi, 
    quadpoints_theta=quadpoints_theta
)
s_plot.save(filename=out_dir / 'plasma_boundary.json')

# Plot initial Bnormal on plasma surface from un-optimized BiotSavart coils
make_Bnormal_plots(bs, s_plot, out_dir, "biot_savart_initial")

# optimize the currents in the TF coils and plot results
bs, _, _, _ = coil_optimization_QA(s, bs, base_curves, curves)
# bs.save('B_TF.json')
currents = np.array([coil.current.get_value() for coil in coils])
curves_to_vtk(curves, out_dir / "TF_0", close=True)
bs.set_points(s.gamma().reshape((-1, 3)))
Bnormal = np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)
B_axis = calculate_on_axis_B(bs, s)
make_Bnormal_plots(bs, s_plot, out_dir, "BTF_0", B_axis)

# Finally, initialize the psc class
kwargs_geo = {"Nx": 10, "out_dir": out_str,
                "initialization": "plasma", 
              "poff": poff,}
              # "interpolated_field": True} 
psc_array = PSCgrid.geo_setup_between_toroidal_surfaces(
    s, coils, s_inner, s_outer,  **kwargs_geo
)
print('Number of PSC locations = ', len(psc_array.grid_xyz))

currents = []
for i in range(psc_array.num_psc):
    currents.append(Current(psc_array.I[i]))
all_coils = coils_via_symmetries(
    psc_array.curves, currents, nfp=psc_array.nfp, stellsym=psc_array.stellsym
)
B_PSC = BiotSavart(all_coils)
# Plot initial errors from only the PSCs, and then together with the TF coils
make_Bnormal_plots(B_PSC, s_plot, out_dir, "biot_savart_PSC_initial", B_axis)
make_Bnormal_plots(bs + B_PSC, s_plot, out_dir, "B_0", B_axis)

# Check SquaredFlux values using different ways to calculate it
x0 = np.ravel(np.array([psc_array.alphas, psc_array.deltas]))
fB = SquaredFlux(s, bs, np.zeros((nphi, ntheta))).J()
fB_TF = fB / (B_axis ** 2 * s.area())
print('fB only TF coils = ', fB_TF)
bs.set_points(s.gamma().reshape(-1, 3))
Bnormal = np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)
print('fB only TF direct = ', np.sum(Bnormal.reshape(-1) ** 2 * psc_array.grid_normalization ** 2
                                    ) / (2 * B_axis ** 2 * s.area()))
make_Bnormal_plots(B_PSC, s_plot, out_dir, "biot_savart_PSC_initial", B_axis)
fB = SquaredFlux(s, B_PSC, np.zeros((nphi, ntheta))).J()
print(fB/ (B_axis ** 2 * s.area()))
fB = SquaredFlux(s, B_PSC + bs, np.zeros((nphi, ntheta))).J()
print('fB with both, before opt = ', fB / (B_axis ** 2 * s.area()))
fB = SquaredFlux(s, B_PSC, -Bnormal).J()
print('fB with both (minus sign), before opt = ', fB / (B_axis ** 2 * s.area()))

# Actually do the minimization now
print('beginning optimization: ')
eps = 1e-6
options = {"disp": True, "maxiter": 10}  # 100
verbose = True

# Run STLSQ with BFGS in the loop
kwargs_manual = {
                 "out_dir": out_str, 
                 "plasma_boundary" : s,
                 "coils_TF" : coils
                 }
I_threshold = 1e5  # 2e4
I_threshold_scaling = 1.2  # 1.2
I_scaling_scaling = 1.0  # 0.999 # 0.997
STLSQ_max_iters = 20  # 60
BdotN2_list = []
Bn_list = []
num_pscs = []
for k in range(STLSQ_max_iters):
    
    # Threshold scale gets exponentially smaller each iteration
    I_threshold_scaling *= I_scaling_scaling
    I_threshold *= I_threshold_scaling
    x0 = np.ravel(np.array([psc_array.alphas, psc_array.deltas]))
    print('Number of PSCs = ', len(x0) // 2, ' in iteration ', k)
    print('I_threshold = ', I_threshold)
    
    # Define the linear bound constraints for each set of angles
    opt_bounds1 = tuple([(-np.pi / 2.0 + eps, np.pi / 2.0 - eps) for i in range(psc_array.num_psc)])
    opt_bounds2 = tuple([(-np.pi + eps, np.pi - eps) for i in range(psc_array.num_psc)])
    opt_bounds = np.vstack((opt_bounds1, opt_bounds2))
    opt_bounds = tuple(map(tuple, opt_bounds))
    t1_min = time.time()
    x_opt = minimize(psc_array.least_squares, 
                     x0, 
                     args=(verbose,),
                     method='L-BFGS-B',
                     bounds=opt_bounds,
                     jac=psc_array.least_squares_jacobian, 
                     options=options,
                     tol=1e-20,  # Required to make progress when fB is small
                     # callback=callback
                     )
    t2_min = time.time()
    print(t2_min - t1_min, ' seconds for optimization')
    
    t1_save = time.time()
    psc_array.setup_curves()
    psc_array.plot_curves('PSCs_Ithresh_{0:.3e}'.format(I_threshold) + '_N{0:d}'.format(psc_array.num_psc) + '_' + str(k + 1))
    currents = []
    for i in range(psc_array.num_psc):
        currents.append(Current(psc_array.I[i]))
    all_coils = coils_via_symmetries(
        psc_array.curves, currents, nfp=psc_array.nfp, stellsym=psc_array.stellsym
    )
    B_PSC = BiotSavart(all_coils)
    B_tot = bs + B_PSC
    # B_tot.save('B_total_Ithresh_{0:.3e}'.format(I_threshold) + '_N{0:d}'.format(psc_array.num_psc) + '.json')
    make_Bnormal_plots(B_tot, s_plot, out_dir, 'B_' + str(k + 1), B_axis)
    t2_save = time.time()
    print(t2_save - t1_save, ' seconds to save all the B field data')
    
    kwargs_manual["alphas"] = psc_array.alphas
    kwargs_manual["deltas"] = psc_array.deltas
    bs, BdotN2, Bn, psc_array = coil_optimization_QA(s, bs, base_curves, curves, psc_array, MAXITER=5, jac_flag=True)
    currents = np.array([coil.current.get_value() for coil in coils])
    curves_to_vtk(curves, out_dir / ("TF_" + str(k + 1)), close=True)
    bs.set_points(s.gamma().reshape((-1, 3)))
    Bnormal = np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)
    make_Bnormal_plots(bs, s_plot, out_dir, "BTF_" + str(k + 1))
    B_tot = bs + B_PSC
    # B_tot.save('B_total_Ithresh_{0:.3e}'.format(I_threshold) + '_N{0:d}'.format(psc_array.num_psc) + '_' + str(k + 1) + '.json')
    make_Bnormal_plots(B_tot, s_plot, out_dir, 'Bjoint_' + str(k + 1), B_axis)
    
    # Do the thresholding and reinitialize a grid without the chopped PSCs
    I = psc_array.I
    grid_xyz = psc_array.grid_xyz
    if len(BdotN2_list) > 0:
        BdotN2_list = np.hstack((BdotN2_list, np.array(psc_array.BdotN2_list)))
        Bn_list = np.hstack((Bn_list, np.array(psc_array.Bn_list)))
        num_pscs = np.hstack((num_pscs, (len(x0) // 2) * np.ones(len(np.array(psc_array.BdotN2_list)))))
    else:
        BdotN2_list = np.array(psc_array.BdotN2_list)
        Bn_list = np.array(psc_array.Bn_list)
        num_pscs = np.array((len(x0) // 2) * np.ones(len(np.array(psc_array.BdotN2_list))))
    
    # Now add BdotN2 from the coils
    BdotN2_list = np.hstack((BdotN2_list, np.array(BdotN2)))
    Bn_list = np.hstack((Bn_list, np.array(Bn)))
    
        
    # big_I_inds = np.ravel(np.where(np.abs(I) > I_threshold))
    # if len(big_I_inds) != psc_array.num_psc:
    #     grid_xyz = grid_xyz[big_I_inds, :]
    #     alphas = alphas[big_I_inds]
    #     deltas = deltas[big_I_inds]
    # else:
    #     print('STLSQ converged, breaking out of loop')
    #     break
    # kwargs_manual["alphas"] = alphas
    # kwargs_manual["deltas"] = deltas
    kwargs_manual["coils_TF"] = bs._coils
    try:
        # print(x_opt.x)
        psc_array = PSCgrid.geo_setup_manual(
            grid_xyz, psc_array.R, **kwargs_manual
        )
        # print(psc_array.alphas, psc_array.deltas)
    except TypeError:
        print('Grid initialization raised TypeError, quitting STLSQ loop')
        break

# Plot the data from optimization
num_pscs = np.ravel(num_pscs)
BdotN2_list = np.ravel(BdotN2_list)
Bn_list = np.ravel(Bn_list)
fig, ax1 = plt.subplots()
color = 'b'
ax1.set_xlabel('Iterations')
ax1.set_ylabel(r'$f_B$', color=color)
ax1.semilogy(BdotN2_list, color=color)
ax1.semilogy(Bn_list, color + '--', label=r'$b_n$')
ax1.semilogy(0.005 * np.ones(len(Bn_list)), 'm--', label=r'$b_n$, benchmark')
ax1.plot(fB_TF * np.ones(len(BdotN2_list)), 'k--', label=r'$f_B$, TF coils only')
ax1.grid()
ax1.tick_params(axis='y', labelcolor=color)
ax1.legend()
ax2 = ax1.twinx()  # instantiate a second Axes that shares the same x-axis
color = 'tab:red'
ax2.set_ylabel('# of PSCs', color=color)  # we already handled the x-label with ax1
ax2.plot(num_pscs, color=color)
ax2.tick_params(axis='y', labelcolor=color)
fig.tight_layout()  # otherwise the right y-label is slightly clipped
plt.savefig(out_dir / 'convergence.jpg')

# Last check that direct f_B calculation is still consistent with the optimization
psc_array.setup_curves()
psc_array.plot_curves('final_')
currents = []
for i in range(psc_array.num_psc):
    currents.append(Current(psc_array.I[i]))
all_coils = coils_via_symmetries(
    psc_array.curves, currents, nfp=psc_array.nfp, stellsym=psc_array.stellsym
)
B_PSC = BiotSavart(all_coils)
fB = SquaredFlux(s, B_PSC + bs, np.zeros((nphi, ntheta))).J()
print('fB with both, after opt = ', fB / (B_axis ** 2 * s.area()))
make_Bnormal_plots(B_PSC, s_plot, out_dir, "PSC_final", B_axis)
make_Bnormal_plots(bs + B_PSC, s_plot, out_dir, "PSC_and_TF_final", B_axis)
t2 = time.time()
print('Total time: ', t2 - t1)
plt.show()

