# GVEC template parameter file
# GVEC v1.0-dev
ProjectName = "SIMSOPT-GVEC-CIRCULAR"
whichInitEquilibrium = 0
init_fromBConly = true
init_LA = true
which_hmap = 1

degGP = 8
X1X2_deg = 5
LA_deg = 5

nfp = 1
fac_nyq = 4
X1_mn_max = [2, 2]
X1_sin_cos = "_cos_"
X2_mn_max = [2, 2]
X2_sin_cos = "_sin_"
LA_mn_max = [2, 2]
LA_sin_cos = "_sin_"

PHIEDGE = 0.0314159265359

MaxIter = 100
start_dt = 0.5
minimize_tol = 1e-6
logIter = 10
PrecondType = 1
MinimizerType = 10

stages = [
    {sgrid.nElems = 3},
    {sgrid.nElems = 9},
]

[sgrid]
grid_type = 4

[iota]
type = "polynomial"
coefs = [1.0]

[pres]
type = "polynomial"
coefs = [1.0]
scale = 1500.0
