---

version: 1

disable_existing_loggers: False

formatters:
    std:
        format: "%(asctime)s %(name)s-%(levelname)s: %(message)s"
    mpi:
        format: "[rank %(rank)s/%(size)s] %(asctime)s %(name)s-%(levelname)s: %(message)s"
    info_stream:
        format: "%(message)s"
    warning_stream:
        format: "%(levelname)s-%(name)s: %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: info_stream
        stream: ext://sys.stdout

    console_warning:
        class: logging.StreamHandler
        level: WARNING
        formatter: warning_stream
        stream: ext://sys.stderr

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: std
        filename: debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    mpi_file_handler:
        class: simsopt.util.mpi_logger.MPILogHandler
        level: DEBUG            
        formatter: mpi
        logfile: debug.log
        # filename: deubg.log
        # maxBytes: 10485760 # 10MB
        # backupCount: 20
        # encoding: utf8

    
#loggers:
#    my_module:
#        level: ERROR
#        handlers: [console]
#        propagate: no


root:
    level: DEBUG
    # Delete either file_handler or mpi_file_handler in init function depending on mpi
    handlers: [console, console_warning, file_handler, mpi_file_handler] 

...
