#!/bin/bash

# This script runs most of the examples. This script is used by the Github
# Actions continuous integration. Examples that can use MPI are run
# for various numbers of processes.

set -ex

# In the next line, ${GITHUB_ACTIONS:+--oversubscribe} evaluates to
# --oversubscribe if the environment variable GITHUB_ACTIONS is set,
# and evaluates to nothing if the variable is not set.  The motivation
# is that Github Actions only gives you 2 processors, so we have to
# "oversubscribe" to test on >2 mpi processes. But we don't want to
# set --oversubscribe when outside Github Actions, since other
# versions of mpi like mpich do not have this flag.
MPI_OPTIONS=${GITHUB_ACTIONS:+--oversubscribe}
echo MPI_OPTIONS=$MPI_OPTIONS

./just_a_quadratic
./surface_volume_and_area
./minimize_curve_length
./qsc

./stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota

./stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota_spec
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota_spec
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota_spec

./stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume

./stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume_spec

./stellopt_scenarios_2DOF_circularCrossSection_varyAxis_targetIotaAndQuasisymmetry

./stellopt_scenarios_2DOF_specOnly_targetIotaAndVolume

./stellopt_scenarios_2DOF_vmecAndSpec
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios_2DOF_vmecAndSpec

./stellopt_scenarios_2DOF_vmecOnly_targetIotaAndVolume
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios_2DOF_vmecOnly_targetIotaAndVolume
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios_2DOF_vmecOnly_targetIotaAndVolume

mpiexec $MPI_OPTIONS -n 2 ./resolution_increase

./eliminate_magnetic_islands
mpiexec $MPI_OPTIONS -n 2 ./eliminate_magnetic_islands
mpiexec $MPI_OPTIONS -n 3 ./eliminate_magnetic_islands

./boozer

mpiexec $MPI_OPTIONS -n 2 ./QH_fixed_resolution
