#!/bin/bash

# This script runs most of the examples. This script is used by the Github
# Actions continuous integration. Examples that can use MPI are run
# for various numbers of processes.

set -ex

# In the next line, ${GITHUB_ACTIONS:+--oversubscribe} evaluates to
# --oversubscribe if the environment variable GITHUB_ACTIONS is set,
# and evaluates to nothing if the variable is not set.  The motivation
# is that Github Actions only gives you 2 processors, so we have to
# "oversubscribe" to test on >2 mpi processes. But we don't want to
# set --oversubscribe when outside Github Actions, since other
# versions of mpi like mpich do not have this flag.
MPI_OPTIONS=${GITHUB_ACTIONS:+--oversubscribe}
echo MPI_OPTIONS=$MPI_OPTIONS

./1_Simple/just_a_quadratic.py
./1_Simple/surface_volume_and_area.py
./1_Simple/minimize_curve_length.py
./2_Intermediate/QSC.py

./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota.py
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota.py
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota.py

./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota_spec.py
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota_spec.py
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyAxis_targetIota_spec.py

./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume.py
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume.py
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume.py

./stellopt_scenarios/stellopt_scenarios_1DOF_circularCrossSection_varyR0_targetVolume_spec.py

./stellopt_scenarios/stellopt_scenarios_2DOF_circularCrossSection_varyAxis_targetIotaAndQuasisymmetry.py

./stellopt_scenarios/stellopt_scenarios_2DOF_specOnly_targetIotaAndVolume.py

./stellopt_scenarios/stellopt_scenarios_2DOF_vmecAndSpec.py
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios/stellopt_scenarios_2DOF_vmecAndSpec.py

./stellopt_scenarios/stellopt_scenarios_2DOF_vmecOnly_targetIotaAndVolume.py
mpiexec $MPI_OPTIONS -n 2 ./stellopt_scenarios/stellopt_scenarios_2DOF_vmecOnly_targetIotaAndVolume.py
mpiexec $MPI_OPTIONS -n 3 ./stellopt_scenarios/stellopt_scenarios_2DOF_vmecOnly_targetIotaAndVolume.py

mpiexec $MPI_OPTIONS -n 2 ./2_Intermediate/resolution_increase.py

./2_Intermediate/eliminate_magnetic_islands.py
mpiexec $MPI_OPTIONS -n 2 ./2_Intermediate/eliminate_magnetic_islands.py
mpiexec $MPI_OPTIONS -n 3 ./2_Intermediate/eliminate_magnetic_islands.py

./2_Intermediate/boozer.py

mpiexec $MPI_OPTIONS -n 2 ./2_Intermediate/QH_fixed_resolution.py
