#!/bin/bash

# This script runs non-MPI examples. This script is used by the Github
# Actions continuous integration.
set -ex

./1_Simple/just_a_quadratic.py
./1_Simple/surf_vol_area.py
./1_Simple/minimize_curve_length.py
./1_Simple/tracing_fieldlines_NCSX.py
./1_Simple/tracing_fieldlines_QA.py
./1_Simple/tracing_particle.py
./1_Simple/qfm.py
./1_Simple/stage_two_optimization_minimal.py
./2_Intermediate/QSC.py
./2_Intermediate/boozer.py
./2_Intermediate/stage_two_optimization.py
./2_Intermediate/stage_two_optimization_stochastic.py
./2_Intermediate/stage_two_optimization_finite_beta.py
./3_Advanced/stage_two_optimization_finitebuild.py
