#!/bin/bash

# This script runs non-MPI examples. This script is used by the Github
# Actions continuous integration. 
set -ex

./1_Simple/just_a_quadratic.py
./1_Simple/surface_volume_and_area.py
./1_Simple/minimize_curve_length.py
./2_Intermediate/QSC.py
./2_Intermediate/boozer.py
