#!/usr/bin/env python

"""
This script solve the problem in
https://github.com/landreman/stellopt_scenarios/tree/master/7DOF_varyAxisAndElongation_targetIotaAndQuasisymmetry
See that website for a detailed description of the problem.
"""

import simsopt as so

vmec = so.Vmec("input.stellopt_scenarios_7dof")

# We will optimize in the space of Garabedian coefficients:
surf = vmec.boundary.to_Garabedian()
vmec.boundary = surf

# Define parameter space:
surf.all_fixed()
surf.fixed_range(mmin=0, mmax=2, nmin=-1, nmax=1, fixed=False)
surf.set_fixed("Delta(1,0)") # toroidally-averaged major radius
surf.set_fixed("Delta(0,0)") # toroidally-averaged minor radius

# Define objective function:
boozer = so.Boozer(vmec, mpol=32, ntor=16)
qs = so.Quasisymmetry(boozer,
                      1.0, # Radius to target
                      1, 0, # (M, N) you want in |B|
                      normalization="symmetric",
                      weight="stellopt")

# Objective function is 100 * (iota - (-0.41))^2 + 1 * (qs - 0)^2
prob = so.LeastSquaresProblem([(vmec.iota_axis, -0.41, 100),
                               (qs, 0, 1)])

residuals = prob.f()
vals = prob.dofs.f()
print("Initial values before shifting and scaling:  ", vals[:10])
print("Initial residuals after shifting and scaling:", residuals[:10])
print("size of residuals:", len(residuals))
print("Initial objective function:", prob.objective())
print("Parameter space:")
for name in prob.dofs.names:
    print(name)
print("Initial state vector:", prob.x)
print("Initial iota on axis:", vmec.iota_axis())
#exit(0)

so.least_squares_serial_solve(prob)

residuals = prob.f()
vals = prob.dofs.f()
print("Final values before shifting and scaling:  ", vals[:10])
print("Final residuals after shifting and scaling:", residuals[:10])
print("Final objective function:", prob.objective())
print("Final state vector:", prob.x)
print("Final iota on axis:", vmec.iota_axis())
