#!/usr/bin/env python3

import logging
import numpy as np
from simsopt import Vmec, Spec, LeastSquaresProblem, least_squares_serial_solve

"""
This script implements the "2DOF_vmecOnly_targetIotaAndVolume" example from
https://github.com/landreman/stellopt_scenarios

This optimization problem has two independent variables, representing
the helical shape of the magnetic axis. The problem also has two
objectives: the plasma volume and the rotational transform on the
magnetic axis.

The resolution in this example (i.e. ns, mpol, and ntor) is somewhat
lower than in the stellopt_scenarios version of the example, just so
this example runs fast.

Details of the optimum and a plot of the objective function landscape
can be found here:
https://github.com/landreman/stellopt_scenarios/tree/master/2DOF_vmecOnly_targetIotaAndVolume
"""

# This next line turns on detailed logging. It can be commented out if
# you do not want such verbose output.
logging.basicConfig(level=logging.INFO)

# Initialize VMEC from an input file:
vmec = Vmec('input.2DOF_vmecOnly_targetIotaAndVolume')
surf = vmec.boundary

# Initialize SPEC from an input file:
spec = Spec('2DOF_targetIotaAndVolume.sp')

# Set the SPEC boundary to be the same object as the VMEC boundary!
spec.boundary = surf

# VMEC parameters are all fixed by default, while surface parameters are all non-fixed by default.
# You can choose which parameters are optimized by setting their 'fixed' attributes.
surf.all_fixed()
surf.set_fixed('rc(1,1)', False)
surf.set_fixed('zs(1,1)', False)

# Each Target is then equipped with a shift and weight, to become a
# term in a least-squares objective function.  A list of terms are
# combined to form a nonlinear-least-squares problem.
desired_volume = 0.15
volume_weight = 1
term1 = (spec.volume, desired_volume, volume_weight)

desired_iota = 0.41
iota_weight = 1
term2 = (vmec.iota_axis, desired_iota, iota_weight)

prob = LeastSquaresProblem([term1, term2])

# Solve the minimization problem:
least_squares_serial_solve(prob)

print("At the optimum,")
print(" objective function = ", prob.objective())
print(" rc(m=1,n=1) = ", surf.get_rc(1, 1))
print(" zs(m=1,n=1) = ", surf.get_zs(1, 1))
print(" volume, according to VMEC    = ", vmec.volume())
print(" volume, according to SPEC    = ", spec.volume())
print(" volume, according to Surface = ", surf.volume())
print(" iota on axis, from VMEC       = ", vmec.iota_axis())
print(" iota at mid-radius, from SPEC = ", spec.iota())

assert np.abs(surf.get_rc(1, 1) - 0.0313066948) < 1.0e-3
assert np.abs(surf.get_zs(1, 1) - (-0.031232391)) < 1.0e-3
assert np.abs(spec.volume() - 0.178091) < 1.0e-3
assert np.abs(vmec.volume() - 0.178091) < 1.0e-3
assert np.abs(surf.volume()  - 0.178091) < 1.0e-3
assert np.abs(vmec.iota_axis() - 0.4114567) < 1.0e-4
assert prob.objective() < 1.0e-2
