{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: simsopt
  version: {{ data.get('version') }}

source:
  path: ..

build:
  include_recipe: False
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja
    # - numpy {{ numpy }}
    # - python 
    # - pip

  host:
    - python
    - pip
    - numpy >=1.19

  run:
    - python
    - numpy >=1.19


test:
  imports:
    - simsopt
  source_files:
    - tests
  commands:
    - ./run_tests 

about:
  summary: simplified framework for stellarator optimization
  license_file: ["COPYING", "COPYING.LESSER"]
