package:
  name: simsopt
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}

source:
  path: ..

build:
  include_recipe: False
  number: 0
  script: 
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - "setuptools_scm[toml]"
    - boost
    - pybind11 <3.0
    - scikit-build-core

  host:
    - pip
    - wheel
    - python {{ python }}
    - scikit-build-core
    - "setuptools_scm[toml]"
    - numpy >=2.0

  run:
    - python
    - numpy
    - jax >=0.2.5
    - jaxlib >=0.1.56
    - scipy >=1.5.4
    - Deprecated >=1.2.10
    - nptyping >=1.3.0
    - monty >=2021.6.10 
    - ruamel.yaml
    - sympy
    - f90nml
    - pyevtk

about:
  home: https://github.com/hiddenSymmetries/simsopt
  summary: simplified framework for stellarator optimization
  license: MIT
  license_file: "LICENSE"
  description:
  doc_url: https://simsopt.readthedocs.io/
  dev_url: https://github.com/hiddenSymmetries/simsopt

extra:
  recipe-maintainers:
    - mbkumar
    - landreman
    - florianwechsung
