{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}

package:
  name: simsopt
  version: {{ version }}

source:
  path: ..

build:
  include_recipe: False
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  host:
    - python
    - pip
    - wheel
    - setuptools
    - numpy >=1.19.0
    - boost >=1.70.0
    - "setuptools_scm[toml]"

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - boost {{ boost }}
    - jax >=0.2.4
    - jaxlib >=0.1.56
    - scipy >=1.5.4
    - Deprecated >=1.2.10
    - nptyping >=1.3.0
    - pandas >=1.1.4
    - monty >=2021.6.10 
    - ruamel.yaml
    - matplotlib
    - sympy
    - f90nml

about:
  home: {{ data.get('url') }}
  summary: simplified framework for stellarator optimization
  license: LGPL
  license_file: ["COPYING", "COPYING.LESSER"]
  description:
  doc_url: https://simsopt.readthedocs.io/
  dev_url: {{ data.get('url') }}

extra:
  recipe-maintainers:
    - mbkumar
    - landreman
    - florianwechsung
