name: Singularity Build
on: 
  push:

    # This recipe shows how to manually define a matrix of singularity recipes (paths) to build
    # Edit the branches here if you want to change deploy behavior
    branches:
      - master
      - mbk/singularity
    tags: 
      - v*

  # Do the builds on all pull requests (to test them)
  pull_request: []

jobs:
  build-test-containers:
    runs-on: ubuntu-latest
    container:
      image: quay.io/singularity/singularity:v3.8.3
    strategy:
      fail-fast: true

    name: Check ${{ matrix.recipe }}
    steps:

      - name: Check out code for the container build
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Step to get tag name
        if: startsWith(github.event.ref, 'refs/tags/v')
        #id: vars
        #run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        run: |
          tag = $(echo "${GITHUB_REF#refs/*/}")
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Step to get tag name
        if: ${{ startsWith(github.ref, 'refs/heads') && github.ref == 'refs/heads/master' }}
        #id: vars
        #run: echo ::set-output name=tag::"latest"
        run: echo "tag=latest" >> $GITHUB_ENV
      
      - name: Step to get tag name
        if: ${{ startsWith(github.ref, 'refs/heads') && github.ref != 'refs/heads/master' }}
        #id: vars
        #run: echo ::set-output name=tag::"test"
        run: echo "tag=test" >> $GITHUB_ENV
      
      - name: Build Container
        run: |
          ls 
          sudo -E singularity build simsopt.sif ci/singularity.def

      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        run: |         
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push simsopt.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
